### ISSUE TITLE
Add possibility to show suggestions for empty textField value

### ISSUE THREAD

**Issue by tamoler** [wbadam/autocomplete-extension#13]
Can you please remove  if (!textField.getValue().isEmpty())  from onInput method in AutocompleteExtensionConnector. Or add some flag that will allow show suggestions for empty string
if (!textField.getValue().isEmpty() || allowEmptyStringSuggestions);

Also would be great if you will make public  showSuggestionsFor(String query); Which will allow programmatically trigger  showing suggestions for some query.

**Comment by wbadam** [comment]
Hi @tamoler,

Thank you for your feedback and sorry for the long delay, I wasn't able to maintain the add-on as I would've liked.

A feature allowing suggestions for empty text fields will be released shortly as part of #21.

Regarding your second suggestion, please see #3. That task is non-trivial due to the way GWT is communicating between the server and client, but there is a detailed discussion and solution branch you could use in that thread.

**Comment by wbadam** [comment]
The fix for the first issue has just been released in 0.2.4.
The second issue could be followed in #3, so I'll close this as duplicate.
