### ISSUE TITLE
Can't get it to run with Vaadin/Spring Boot

### ISSUE THREAD

**Issue by jonmartinsolaas** [wbadam/autocomplete-extension#5]
Using

`		<dependency>
			<groupId>org.vaadin.spring.addons</groupId>
			<artifactId>vaadin-spring-addon-sidebar</artifactId>
			<version>2.0.0-SNAPSHOT</version>
		</dependency>`

in an app generated by Spring Initializr (Boot 1.5.2) the suggestions are not triggered for me. Works fine in a minimum app generated from the Vaadin archetype.

I would expect the error to be on me, but in this case the api is so clean and simple so I really don't understand how I can have messed it up :)

**Comment by wbadam** [comment]
Hi,

It is possibly due to the widgetset not having been compiled. You may see an error on the console saying that AutocompleteExtension isn't found in DefaultWidgetSet.

To solve this, you need to compile the widgetset during build. Please add the highlighted plugins to your pom.xml and rebuild your application: https://github.com/joshlong/vaadin-and-spring-talk/blob/master/pom.xml#L117-L181

You can find more info in this forum thread https://vaadin.com/forum#!/thread/9587133

Please let me know if that helped.

**Comment by jonmartinsolaas** [comment]
That did the trick, thanks a bunch!

**Comment by wbadam** [comment]
Awesome! No worries, happy to help.
